spring.application.name=springboot_crud
spring.datasource.url=jdbc:postgresql://localhost:5432/springboot_crud
spring.datasource.username=postgres
spring.datasource.password=9148
spring.jpa.hibernate.ddl-auto=update
server.port=8081
